### Exercice 1:

Write a function that takes a string, and two indexes (integers), and returns a slice of that string as well as the length of the string.
Call the function, and store the results in two variables

In [16]:
#Declare the function
def function1(c , a ,b):
    n = len(c)
    return c[a:b] , n
#Call the function
c = "hello  hy gyuhb "
a = 2
b = 3

#print the result in a well formated format
print(function1(c ,a , b))


### Exercice 2:

1. Write a function that takes two arguments, and returns the sum of the two.
2. Call the function with the values 1 and 2.1, then check the type of the result.
3. Call the function with the values False and 2, then check the type of the result.

In [2]:
#Declare the function
def somme(a , b):
    t =  (a,b)
    return sum(t)



#Call with the values 1 and two
a = 1
b = 2

#Check the type of the result
print(somme(a,b))

3


### Exercice 3:

Write a function that takes a string and returns a dictionary containing character frequency.

*example*

    string sample: 'test'
    
    expected result: {'t':2, 'e':1, 's':1}

In [17]:
#Declare the function
def dic(c):
    b = {a:c.count(a) for a in c}
    return b
c ='test'
print(dic(c))


{'t': 2, 'e': 1, 's': 1}


### Exercice 4:

Given two lists, iterate both lists simultaniously, such the first list would display item in original order and the second list in reverse order

*example*:

In [3]:
from lib import print_orl #this is a lib you dont have access to
print_orl([1,2,3],[1,2,3])

1 3
2 2
3 1


In [1]:
def orl(L ,X):
    n = len(L)
    for i in range(n):
        print(L[i] , X[n-i-1])
L=[1,2,3]
X=[1,2,3]
orl(L,X)
       

1 3
2 2
3 1


### Exercice 5:

Given two 2d arrays, stack them horizontally.

*example:*

In [15]:
import numpy as np

#The input
a = np.ones((1, 10)).reshape(2, -1)
b = np.zeros((1, 10)).reshape(2, -1)

#Try to print input
print(a)
print(b)


#concatenate horizontally
#output shoul look like:     array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
#                                   [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

z = np.concatenate([[np.concatenate([a[0] , b[0]])],[ np.concatenate([a[1] , b[1]])]])
print(z)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]]


### exercice 6:

Create the following patterns using the bellow arrays a and b, and numpy functions:

In [121]:
import  numpy as np
a = np.arange(3)
b = np.ones((3,3,3))

#output1 the following array: array([0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
#z = np.full((1,3), [2,2,2])
d= np.concatenate((np.zeros(3) , np.ones(3) , np.ones(3)+np.ones(3), a , a , a) ,axis = 0)
print(d)
#output2 the follwing array: array([[[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]]])
#d = np.array([1, 2, 3], ndmin=3)
#print(d.reshape((3,3)))
a+b  

#output3 array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.]])


np.reshape(b , [3 , -1])


[0. 0. 0. 1. 1. 1. 2. 2. 2. 0. 1. 2. 0. 1. 2. 0. 1. 2.]


array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])